# Generated by Django 3.2.5 on 2021-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='store',
            name='thestore_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
