# Generated by Django 3.2.5 on 2021-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210715_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
